language: node_js
node_js:
- '6.0'
install:
- npm install
before_deploy:
- make
deploy:
  provider: elasticbeanstalk
  access-key-id: AKIAJIJDN7CQWMJ2ZTIQ
  secret-access-key:
    secure: FBtCbtIS10mGRWfgjyzNwlxpi/JgdVUinrQey2h1g/KL823886YS6hjnbXmt4mdu8m81Dyzyx2N5+xWqCq60rAudGZj7BHXOX43+7PmRTVeHw8j8VJZMcc9Yvpx1IAwwGeUUgE8pd5cM6nO7H7VNXvfKduOhajpveXbyjRgk9YY=
  region: us-east-1
  app: training-dlc
  env: trainingDlc-env
  zip_file: training-dlc.zip
  bucket_name: elasticbeanstalk-us-east-1-608492894188
  on:
    repo: KinveyClientServices/training-dlc
    branch: feature/travis