language: node_js
node_js:
- 6.0
install:
- npm install
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: Il+dcSmd2X8oikfLaFwTfkzM+ssDTxP4EG5udgZDxGDY7bNiZiDIV0OP49spl5c5JVxb67OnOl3RQOR3Ajgun1V4kOr7BDgAsM2wMs8FWYPchfGXXIXEcq7GYuFSFzDEzDBDUQ9AQTRJR9FLNXl9xJv8EvAA1IE0ovz9aMuXomM=
  secret_access_key:
    secure: SG5/IiItePA5DpJnW77c3q/FtHY6gxM++AOluE4rwIKdAv9b9bQBcwn5oZD4WBb/LvYjY9mNZvUPSoFoIaYuQO1t/3PIciEmaeS6BViyzJ3SYGMaSPmVKqR6c+QtgJo3Wvci4Nfyqi47E8AlImdMuGVmCIXbka2NCwpBjYCrHHU=
  region: us-east-1
  app: training-dlc
  env: trainingDlc-env
  bucket_name: elasticbeanstalk-us-east-1-608492894188
  on:
    repo: training-dlc
    branch: develop